// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYf-kq7PoGz3UifNOrBVzT6bmburV_LO0',
    appId: '1:447005106097:web:1fbf1ed259983cab98a790',
    messagingSenderId: '447005106097',
    projectId: 'hv-notes',
    authDomain: 'hv-notes.firebaseapp.com',
    storageBucket: 'hv-notes.appspot.com',
    measurementId: 'G-VK0W4RVNLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrOnPoMiRWlnqiyNdROUUlI9ytVtgDZ4',
    appId: '1:447005106097:android:1b7ca04e1d66f25998a790',
    messagingSenderId: '447005106097',
    projectId: 'hv-notes',
    storageBucket: 'hv-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMlHa1d8UIRjv8QWM0AZfop5qs54RckM',
    appId: '1:447005106097:ios:05383e7d39ecf36a98a790',
    messagingSenderId: '447005106097',
    projectId: 'hv-notes',
    storageBucket: 'hv-notes.appspot.com',
    iosClientId: '447005106097-r29i7dmcor362uk89r1isdnkb6nopmps.apps.googleusercontent.com',
    iosBundleId: 'com.harsh.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMlHa1d8UIRjv8QWM0AZfop5qs54RckM',
    appId: '1:447005106097:ios:05383e7d39ecf36a98a790',
    messagingSenderId: '447005106097',
    projectId: 'hv-notes',
    storageBucket: 'hv-notes.appspot.com',
    iosClientId: '447005106097-r29i7dmcor362uk89r1isdnkb6nopmps.apps.googleusercontent.com',
    iosBundleId: 'com.harsh.note',
  );
}
